---
# tasks file for roles/database
- name: Launch database container
  docker_container:
    name: my-db
    image: "clarinka/tp-devops-database:latest"
    networks:
      - name: my-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    state: started
    restart_policy: always