---
# tasks file for roles/proxy
- name: Run the HTTP server container
  community.general.docker_container:
    name: httpd
    image: "clarinka/tp-devops-httpd:latest"
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks_cli_compatible: yes
    networks:
      - name: my-network